export interface MCCCode {
  code: string;
  description: string;
  category: string;
}

export const MCC_CATEGORIES = [
  "All Categories",
  "Airlines, Airports",
  "Associations/Organizations",
  "Automobile Dealers and Stores",
  "Automobile Rental",
  "Business Services",
  "Clothing Stores",
  "Contracted Services",
  "Educational Services and Child Care",
  "Entertainment Services",
  "Financial & Real Estate Services",
  "Food, Drug, Liquor Stores, Restaurants and Bars",
  "Hotels and Motels, and other Lodging",
  "Medical Services",
  "Miscellaneous Stores",
  "Personal Services",
  "Repair and Other Rental Services",
  "Retail Stores",
  "Transportation",
  "Utilities",
  "Wholesale Distributors and Manufacturers",
] as const;

export const MCC_CODES: MCCCode[] = [
  // Professional / Agricultural
  { code: "0742", description: "Veterinary Services", category: "Personal Services" },
  { code: "0763", description: "Agricultural Co-operatives", category: "Associations/Organizations" },
  { code: "0780", description: "Horticultural and Landscape Services", category: "Contracted Services" },

  // Contractors
  { code: "1520", description: "General Contractors/Residential and Commercial", category: "Contracted Services" },
  { code: "1711", description: "Air Conditioning, Heating, and Plumbing Contractors", category: "Contracted Services" },
  { code: "1731", description: "Electrical Contractors", category: "Contracted Services" },
  { code: "1740", description: "Insulation, Masonry, Plastering, and Tile Settings Contractors", category: "Contracted Services" },
  { code: "1750", description: "Carpentry Contractors", category: "Contracted Services" },
  { code: "1761", description: "Roofing and Siding, Sheet Metal Work - Contractors", category: "Contracted Services" },
  { code: "1771", description: "Contractors - Concrete Work", category: "Contracted Services" },
  { code: "1799", description: "Contractors, Special Trade (not listed elsewhere)", category: "Contracted Services" },

  // Publishing
  { code: "2741", description: "Miscellaneous Publishing and Printing", category: "Business Services" },
  { code: "2791", description: "Typesetting, Plate Making and Related Services", category: "Business Services" },
  { code: "2842", description: "Specialty Cleaning, Polishing and Sanitation Preparations", category: "Business Services" },

  // Airlines (key ones)
  { code: "3000", description: "United Airlines", category: "Airlines, Airports" },
  { code: "3001", description: "American Airlines", category: "Airlines, Airports" },
  { code: "3058", description: "Delta", category: "Airlines, Airports" },
  { code: "3063", description: "US Airways", category: "Airlines, Airports" },
  { code: "3066", description: "Southwest Airlines", category: "Airlines, Airports" },
  { code: "3174", description: "JetBlue", category: "Airlines, Airports" },
  { code: "3175", description: "Middle East Air", category: "Airlines, Airports" },
  { code: "3246", description: "Ryanair", category: "Airlines, Airports" },
  { code: "3256", description: "Alaska Airlines", category: "Airlines, Airports" },
  { code: "3261", description: "Air China", category: "Airlines, Airports" },

  // Car Rental (key ones)
  { code: "3351", description: "Affiliated Auto Rental", category: "Automobile Rental" },
  { code: "3357", description: "Hertz Rent-A-Car", category: "Automobile Rental" },
  { code: "3366", description: "Budget Rent-A-Car", category: "Automobile Rental" },
  { code: "3385", description: "National Car Rental", category: "Automobile Rental" },
  { code: "3389", description: "Avis Rent-A-Car", category: "Automobile Rental" },
  { code: "3390", description: "Dollar Rent-A-Car", category: "Automobile Rental" },
  { code: "3393", description: "National Car Rental", category: "Automobile Rental" },
  { code: "3395", description: "Thrifty Rent-A-Car", category: "Automobile Rental" },
  { code: "3405", description: "Enterprise Rent-A-Car", category: "Automobile Rental" },

  // Hotels (key ones)
  { code: "3501", description: "Holiday Inn Express / Holiday Inn", category: "Hotels and Motels, and other Lodging" },
  { code: "3502", description: "Best Western Hotels", category: "Hotels and Motels, and other Lodging" },
  { code: "3504", description: "Hilton Hotels", category: "Hotels and Motels, and other Lodging" },
  { code: "3509", description: "Marriott", category: "Hotels and Motels, and other Lodging" },
  { code: "3640", description: "Hyatt Hotel", category: "Hotels and Motels, and other Lodging" },
  { code: "3692", description: "Doubletree Hotels", category: "Hotels and Motels, and other Lodging" },
  { code: "3695", description: "Embassy Suites", category: "Hotels and Motels, and other Lodging" },
  { code: "3715", description: "Fairfield Inn", category: "Hotels and Motels, and other Lodging" },
  { code: "3780", description: "Disney Resorts", category: "Hotels and Motels, and other Lodging" },

  // Transportation
  { code: "4011", description: "Railroads", category: "Transportation" },
  { code: "4111", description: "Local and Suburban Commuter Passenger Transportation", category: "Transportation" },
  { code: "4112", description: "Passenger Railways", category: "Transportation" },
  { code: "4119", description: "Ambulance Services", category: "Transportation" },
  { code: "4121", description: "Taxicabs and Limousines", category: "Transportation" },
  { code: "4131", description: "Bus Lines, Including Charters, Tour Buses", category: "Transportation" },
  { code: "4214", description: "Moving and Storage Companies, Trucking", category: "Transportation" },
  { code: "4215", description: "Courier Services - Air or Ground", category: "Transportation" },
  { code: "4225", description: "Public Warehousing, Storage", category: "Transportation" },
  { code: "4411", description: "Cruise Lines", category: "Transportation" },
  { code: "4457", description: "Boat Rentals and Leases", category: "Transportation" },
  { code: "4468", description: "Marinas, Marine Service, and Supplies", category: "Transportation" },
  { code: "4511", description: "Airlines, Air Carriers (not listed elsewhere)", category: "Airlines, Airports" },
  { code: "4582", description: "Airports, Airport Terminals, Flying Fields", category: "Airlines, Airports" },
  { code: "4722", description: "Travel Agencies and Tour Operations", category: "Transportation" },
  { code: "4723", description: "Package Tour Operators", category: "Transportation" },
  { code: "4784", description: "Tolls, Road and Bridge Fees", category: "Transportation" },
  { code: "4789", description: "Transportation Services (not listed elsewhere)", category: "Transportation" },

  // Telecom / Utilities
  { code: "4812", description: "Telecommunications Equipment including telephone sales", category: "Utilities" },
  { code: "4813", description: "Special Telecom Merchants", category: "Utilities" },
  { code: "4814", description: "Telecommunication services, Fax services", category: "Utilities" },
  { code: "4815", description: "MasterPhone, VisaPhone", category: "Utilities" },
  { code: "4816", description: "Computer Network/Information Services", category: "Utilities" },
  { code: "4821", description: "Telegraph services", category: "Utilities" },
  { code: "4829", description: "Money Orders - Wire Transfer", category: "Utilities" },
  { code: "4899", description: "Cable and Other Pay Television", category: "Utilities" },
  { code: "4900", description: "Electric, Gas, Sanitary and Water Utilities", category: "Utilities" },

  // Wholesale
  { code: "5013", description: "Motor vehicle supplies and new parts", category: "Wholesale Distributors and Manufacturers" },
  { code: "5021", description: "Office and Commercial Furniture", category: "Wholesale Distributors and Manufacturers" },
  { code: "5039", description: "Construction Materials, not listed elsewhere", category: "Wholesale Distributors and Manufacturers" },
  { code: "5044", description: "Office, Photographic, Photocopy Equipment", category: "Wholesale Distributors and Manufacturers" },
  { code: "5045", description: "Computers, Computer Peripheral Equipment, Software", category: "Wholesale Distributors and Manufacturers" },
  { code: "5046", description: "Commercial Equipment, not listed elsewhere", category: "Wholesale Distributors and Manufacturers" },
  { code: "5047", description: "Laboratory/Medical/Dental/Ophthalmic Equipment", category: "Wholesale Distributors and Manufacturers" },
  { code: "5051", description: "Metal Service Centers and Offices", category: "Wholesale Distributors and Manufacturers" },
  { code: "5065", description: "Electrical Parts and Equipment", category: "Wholesale Distributors and Manufacturers" },
  { code: "5072", description: "Hardware Equipment and Supplies", category: "Wholesale Distributors and Manufacturers" },
  { code: "5074", description: "Plumbing and Heating Equipment and Supplies", category: "Wholesale Distributors and Manufacturers" },
  { code: "5085", description: "Industrial Supplies not listed elsewhere", category: "Wholesale Distributors and Manufacturers" },
  { code: "5094", description: "Precious Stones and Metals, Watches and Jewelry", category: "Wholesale Distributors and Manufacturers" },
  { code: "5099", description: "Durable Goods not listed elsewhere", category: "Wholesale Distributors and Manufacturers" },
  { code: "5111", description: "Stationery, Office Supplies, Printing Paper", category: "Wholesale Distributors and Manufacturers" },
  { code: "5122", description: "Drugs, Drug Proprietors, and Druggist's Sundries", category: "Wholesale Distributors and Manufacturers" },
  { code: "5131", description: "Piece Goods, Notions, and Other Dry Goods", category: "Wholesale Distributors and Manufacturers" },
  { code: "5137", description: "Uniforms and Commercial Clothing", category: "Wholesale Distributors and Manufacturers" },
  { code: "5139", description: "Commercial Footwear", category: "Wholesale Distributors and Manufacturers" },
  { code: "5169", description: "Chemicals and Allied Products", category: "Wholesale Distributors and Manufacturers" },
  { code: "5172", description: "Petroleum and Petroleum Products", category: "Wholesale Distributors and Manufacturers" },
  { code: "5192", description: "Books, Periodicals, and Newspapers", category: "Wholesale Distributors and Manufacturers" },
  { code: "5193", description: "Florists' Supplies, Nursery Stock and Flowers", category: "Wholesale Distributors and Manufacturers" },
  { code: "5198", description: "Paints, Varnishes, and Supplies", category: "Wholesale Distributors and Manufacturers" },
  { code: "5199", description: "Non-durable Goods, not listed elsewhere", category: "Wholesale Distributors and Manufacturers" },

  // Retail - Home
  { code: "5200", description: "Home Supply Warehouse Stores", category: "Retail Stores" },
  { code: "5211", description: "Lumber and Building Materials Stores", category: "Retail Stores" },
  { code: "5231", description: "Glass, Paint, and Wallpaper Stores", category: "Retail Stores" },
  { code: "5251", description: "Hardware Stores", category: "Retail Stores" },
  { code: "5261", description: "Nurseries - Lawn and Garden Supply Store", category: "Retail Stores" },
  { code: "5262", description: "Marketplaces", category: "Retail Stores" },
  { code: "5271", description: "Mobile Home Dealers", category: "Retail Stores" },

  // Retail - General
  { code: "5300", description: "Wholesale Clubs", category: "Retail Stores" },
  { code: "5309", description: "Duty Free Store", category: "Retail Stores" },
  { code: "5310", description: "Discount Stores", category: "Retail Stores" },
  { code: "5311", description: "Department Stores", category: "Retail Stores" },
  { code: "5331", description: "Variety Stores", category: "Retail Stores" },
  { code: "5399", description: "Misc. General Merchandise", category: "Retail Stores" },

  // Food & Grocery
  { code: "5411", description: "Grocery Stores, Supermarkets", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5422", description: "Freezer and Locker Meat Provisioners", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5441", description: "Candy, Nut, and Confectionery Stores", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5451", description: "Dairy Products Stores", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5462", description: "Bakeries", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5499", description: "Miscellaneous Food Stores - Convenience Stores", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },

  // Auto
  { code: "5511", description: "Car and Truck Dealers (New and Used)", category: "Automobile Dealers and Stores" },
  { code: "5521", description: "Car and Truck Dealers (Used Only)", category: "Automobile Dealers and Stores" },
  { code: "5531", description: "Auto and Home Supply Stores", category: "Automobile Dealers and Stores" },
  { code: "5532", description: "Automotive Tire Stores", category: "Automobile Dealers and Stores" },
  { code: "5533", description: "Automotive Parts, Accessories Stores", category: "Automobile Dealers and Stores" },
  { code: "5541", description: "Service Stations", category: "Automobile Dealers and Stores" },
  { code: "5542", description: "Automated Fuel Dispensers", category: "Automobile Dealers and Stores" },
  { code: "5551", description: "Boat Dealers", category: "Automobile Dealers and Stores" },
  { code: "5552", description: "Electric Vehicle Charging", category: "Automobile Dealers and Stores" },
  { code: "5561", description: "Camper, Recreational and Utility Trailer Dealers", category: "Automobile Dealers and Stores" },
  { code: "5571", description: "Motorcycle Shops and Dealers", category: "Automobile Dealers and Stores" },
  { code: "5592", description: "Motor Home Dealers", category: "Automobile Dealers and Stores" },
  { code: "5598", description: "Snowmobile Dealers", category: "Automobile Dealers and Stores" },
  { code: "5599", description: "Misc. Automotive, Aircraft and Farm Equipment Dealers", category: "Automobile Dealers and Stores" },

  // Clothing
  { code: "5611", description: "Men's and Boy's Clothing and Accessories Stores", category: "Clothing Stores" },
  { code: "5621", description: "Women's Ready-to-Wear Stores", category: "Clothing Stores" },
  { code: "5631", description: "Women's Accessory and Specialty Shops", category: "Clothing Stores" },
  { code: "5641", description: "Children's and Infant's Wear Stores", category: "Clothing Stores" },
  { code: "5651", description: "Family Clothing Stores", category: "Clothing Stores" },
  { code: "5655", description: "Sports Apparel, Riding Apparel Stores", category: "Clothing Stores" },
  { code: "5661", description: "Shoe Stores", category: "Clothing Stores" },
  { code: "5681", description: "Furriers and Fur Shops", category: "Clothing Stores" },
  { code: "5691", description: "Men's and Women's Clothing Stores", category: "Clothing Stores" },
  { code: "5697", description: "Tailors, Seamstress, Mending, and Alterations", category: "Clothing Stores" },
  { code: "5698", description: "Wig and Toupee Stores", category: "Clothing Stores" },
  { code: "5699", description: "Miscellaneous Apparel and Accessory Shops", category: "Clothing Stores" },

  // Home Furnishings
  { code: "5712", description: "Furniture, Home Furnishings and Equipment Stores", category: "Retail Stores" },
  { code: "5713", description: "Floor Covering Stores", category: "Retail Stores" },
  { code: "5714", description: "Drapery, Window Covering and Upholstery Stores", category: "Retail Stores" },
  { code: "5718", description: "Fireplace, Fireplace Screens, and Accessories Stores", category: "Retail Stores" },
  { code: "5719", description: "Miscellaneous Home Furnishing Specialty Stores", category: "Retail Stores" },
  { code: "5722", description: "Household Appliance Stores", category: "Retail Stores" },
  { code: "5723", description: "Firearm and Ammunition Stores", category: "Retail Stores" },
  { code: "5732", description: "Electronic Sales", category: "Retail Stores" },
  { code: "5733", description: "Music Stores, Musical Instruments, Piano Sheet Music", category: "Retail Stores" },
  { code: "5734", description: "Computer Software Stores", category: "Retail Stores" },
  { code: "5735", description: "Record Shops", category: "Retail Stores" },

  // Eating / Drinking
  { code: "5811", description: "Caterers", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5812", description: "Eating Places and Restaurants", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5813", description: "Bars, Taverns, Cocktail Lounges, Nightclubs", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5814", description: "Fast Food Restaurants", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },

  // Digital
  { code: "5815", description: "Digital Media - Books, Movies, Music", category: "Retail Stores" },
  { code: "5816", description: "Digital Games", category: "Retail Stores" },
  { code: "5817", description: "Digital Applications (Excludes Games)", category: "Retail Stores" },
  { code: "5818", description: "Digital Goods - Large Digital Goods Merchant", category: "Retail Stores" },

  // Drug / Misc
  { code: "5912", description: "Drug Stores and Pharmacies", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5921", description: "Package Stores - Beer, Wine, and Liquor", category: "Food, Drug, Liquor Stores, Restaurants and Bars" },
  { code: "5931", description: "Used Merchandise and Secondhand Stores", category: "Miscellaneous Stores" },
  { code: "5932", description: "Antique Shops", category: "Miscellaneous Stores" },
  { code: "5933", description: "Pawn Shops", category: "Miscellaneous Stores" },
  { code: "5935", description: "Wrecking and Salvage Yards", category: "Miscellaneous Stores" },
  { code: "5937", description: "Antique Reproduction Stores", category: "Miscellaneous Stores" },
  { code: "5940", description: "Bicycle Shops - Sales and Service", category: "Miscellaneous Stores" },
  { code: "5941", description: "Sporting Goods Stores", category: "Miscellaneous Stores" },
  { code: "5942", description: "Book Stores", category: "Miscellaneous Stores" },
  { code: "5943", description: "Stationery Stores, Office and School Supply Stores", category: "Miscellaneous Stores" },
  { code: "5944", description: "Watch, Clock, Jewelry, and Silverware Stores", category: "Miscellaneous Stores" },
  { code: "5945", description: "Hobby, Toy, and Game Shops", category: "Miscellaneous Stores" },
  { code: "5946", description: "Camera and Photographic Supply Stores", category: "Miscellaneous Stores" },
  { code: "5947", description: "Gift, Card, Novelty, and Souvenir Shops", category: "Miscellaneous Stores" },
  { code: "5948", description: "Luggage and Leather Goods Stores", category: "Miscellaneous Stores" },
  { code: "5949", description: "Sewing, Needle, Fabric, and Piece Goods Stores", category: "Miscellaneous Stores" },
  { code: "5950", description: "Glassware/Crystal Stores", category: "Miscellaneous Stores" },

  // Direct Marketing
  { code: "5960", description: "Direct Marketing - Insurance Service", category: "Miscellaneous Stores" },
  { code: "5961", description: "Mail Order Houses Including Catalog Order Stores", category: "Miscellaneous Stores" },
  { code: "5962", description: "Direct Marketing - Travel", category: "Miscellaneous Stores" },
  { code: "5963", description: "Door-to-Door Sales", category: "Miscellaneous Stores" },
  { code: "5964", description: "Direct Marketing - Catalog Merchant", category: "Miscellaneous Stores" },
  { code: "5965", description: "Direct Marketing - Catalog and Retail Merchant", category: "Miscellaneous Stores" },
  { code: "5966", description: "Direct Marketing - Outbound Telemarketing", category: "Miscellaneous Stores" },
  { code: "5967", description: "Direct Marketing - Inbound Teleservices", category: "Miscellaneous Stores" },
  { code: "5968", description: "Direct Marketing - Continuity/Subscription", category: "Miscellaneous Stores" },
  { code: "5969", description: "Direct Marketing - not listed elsewhere", category: "Miscellaneous Stores" },

  // Specialty Retail
  { code: "5970", description: "Artist's Supply and Craft Shops", category: "Miscellaneous Stores" },
  { code: "5971", description: "Art Dealers and Galleries", category: "Miscellaneous Stores" },
  { code: "5972", description: "Stamp and Coin Stores", category: "Miscellaneous Stores" },
  { code: "5973", description: "Religious Goods Stores", category: "Miscellaneous Stores" },
  { code: "5975", description: "Hearing Aids - Sales, Service, and Supply Stores", category: "Miscellaneous Stores" },
  { code: "5976", description: "Orthopedic Goods Prosthetic Devices", category: "Miscellaneous Stores" },
  { code: "5977", description: "Cosmetic Stores", category: "Miscellaneous Stores" },
  { code: "5978", description: "Typewriter Stores", category: "Miscellaneous Stores" },
  { code: "5983", description: "Fuel - Fuel Oil, Wood, Coal, Liquefied Petroleum", category: "Miscellaneous Stores" },
  { code: "5992", description: "Florists", category: "Miscellaneous Stores" },
  { code: "5993", description: "Cigar Stores and Stands", category: "Miscellaneous Stores" },
  { code: "5994", description: "News Dealers and Newsstands", category: "Miscellaneous Stores" },
  { code: "5995", description: "Pet Shops, Pet Foods and Supplies Stores", category: "Miscellaneous Stores" },
  { code: "5996", description: "Swimming Pools - Sales, Service and Supplies", category: "Miscellaneous Stores" },
  { code: "5997", description: "Electric Razor Stores", category: "Miscellaneous Stores" },
  { code: "5998", description: "Tent and Awning Shops", category: "Miscellaneous Stores" },
  { code: "5999", description: "Miscellaneous and Specialty Retail Stores", category: "Miscellaneous Stores" },

  // Financial Services
  { code: "6010", description: "Member Financial Institutions - Manual Cash Disbursements", category: "Financial & Real Estate Services" },
  { code: "6011", description: "Member Financial Institutions - Automated Cash Disbursements", category: "Financial & Real Estate Services" },
  { code: "6012", description: "Member Financial Institutions - Merchandise and Services", category: "Financial & Real Estate Services" },
  { code: "6050", description: "Quasi Cash - Member Financial Institution", category: "Financial & Real Estate Services" },
  { code: "6051", description: "Quasi Cash - Merchant", category: "Financial & Real Estate Services" },
  { code: "6211", description: "Security Brokers/Dealers", category: "Financial & Real Estate Services" },
  { code: "6300", description: "Insurance Sales, Underwriting, and Premiums", category: "Financial & Real Estate Services" },
  { code: "6381", description: "Insurance Premiums", category: "Financial & Real Estate Services" },
  { code: "6399", description: "Insurance, not listed elsewhere", category: "Financial & Real Estate Services" },
  { code: "6513", description: "Real Estate Agents and Managers - Rentals", category: "Financial & Real Estate Services" },
  { code: "6529", description: "Remote Stored Value Load - Member Financial Institution", category: "Financial & Real Estate Services" },
  { code: "6530", description: "Remote Stored Value Load - Merchant", category: "Financial & Real Estate Services" },
  { code: "6531", description: "Payment Service Provider - Money Transfer", category: "Financial & Real Estate Services" },
  { code: "6532", description: "Payment Service Provider - Member Financial Institution", category: "Financial & Real Estate Services" },
  { code: "6533", description: "Payment Service Provider - Merchant", category: "Financial & Real Estate Services" },
  { code: "6534", description: "Money Transfer - Member Financial Institution", category: "Financial & Real Estate Services" },
  { code: "6535", description: "Value Purchase - Member Financial Institution", category: "Financial & Real Estate Services" },
  { code: "6540", description: "POI Funding Transactions", category: "Financial & Real Estate Services" },

  // Hotels/Lodging (general)
  { code: "7011", description: "Hotels, Motels, and Resorts (not listed elsewhere)", category: "Hotels and Motels, and other Lodging" },
  { code: "7012", description: "Timeshares", category: "Hotels and Motels, and other Lodging" },
  { code: "7032", description: "Sporting and Recreational Camps", category: "Hotels and Motels, and other Lodging" },
  { code: "7033", description: "Trailer Parks and Camp Grounds", category: "Hotels and Motels, and other Lodging" },

  // Personal Services
  { code: "7210", description: "Laundry, Cleaning, and Garment Services", category: "Personal Services" },
  { code: "7211", description: "Laundry - Family and Commercial", category: "Personal Services" },
  { code: "7216", description: "Dry Cleaners", category: "Personal Services" },
  { code: "7217", description: "Carpet and Upholstery Cleaning", category: "Personal Services" },
  { code: "7221", description: "Photographic Studios", category: "Personal Services" },
  { code: "7230", description: "Barber and Beauty Shops", category: "Personal Services" },
  { code: "7251", description: "Shoe Repair/Hat Cleaning", category: "Personal Services" },
  { code: "7261", description: "Funeral Service, Crematories", category: "Personal Services" },
  { code: "7273", description: "Dating and Escort Services", category: "Personal Services" },
  { code: "7276", description: "Tax Preparation Service", category: "Personal Services" },
  { code: "7277", description: "Counseling Service - Debt, Marriage, Personal", category: "Personal Services" },
  { code: "7278", description: "Buying/Shopping Services, Clubs", category: "Personal Services" },
  { code: "7296", description: "Clothing Rental - Costumes, Formal Wear, Uniforms", category: "Personal Services" },
  { code: "7297", description: "Massage Parlors", category: "Personal Services" },
  { code: "7298", description: "Health and Beauty Shops", category: "Personal Services" },
  { code: "7299", description: "Miscellaneous Personal Services", category: "Personal Services" },

  // Business Services
  { code: "7311", description: "Advertising Services", category: "Business Services" },
  { code: "7321", description: "Consumer Credit Reporting Agencies", category: "Business Services" },
  { code: "7322", description: "Collection Agencies", category: "Business Services" },
  { code: "7332", description: "Blueprinting and Photocopying Services", category: "Business Services" },
  { code: "7333", description: "Commercial Photography, Art and Graphics", category: "Business Services" },
  { code: "7338", description: "Quick Copy, Reproduction and Blueprinting Services", category: "Business Services" },
  { code: "7339", description: "Stenographic and Secretarial Support Services", category: "Business Services" },
  { code: "7342", description: "Exterminating and Disinfecting Services", category: "Business Services" },
  { code: "7349", description: "Cleaning and Maintenance, Janitorial Services", category: "Business Services" },
  { code: "7361", description: "Employment Agencies, Temporary Help Services", category: "Business Services" },
  { code: "7372", description: "Computer Programming", category: "Business Services" },
  { code: "7375", description: "Information Retrieval Services", category: "Business Services" },
  { code: "7379", description: "Computer Maintenance and Repair Services", category: "Business Services" },
  { code: "7392", description: "Consulting, Public Relations Services", category: "Business Services" },
  { code: "7393", description: "Detective Agencies", category: "Business Services" },
  { code: "7394", description: "Equipment Rental and Leasing Services", category: "Business Services" },
  { code: "7395", description: "Photo Developing, Photo Finishing Laboratories", category: "Business Services" },
  { code: "7399", description: "Misc. Business Services", category: "Business Services" },

  // Auto Services
  { code: "7511", description: "Truck Stop Transactions", category: "Repair and Other Rental Services" },
  { code: "7512", description: "Car Rental Companies (Not Listed Below)", category: "Automobile Rental" },
  { code: "7513", description: "Truck and Utility Trailer Rentals", category: "Automobile Rental" },
  { code: "7519", description: "Recreational Vehicle Rentals", category: "Automobile Rental" },
  { code: "7523", description: "Parking Lots and Garages", category: "Repair and Other Rental Services" },
  { code: "7531", description: "Automotive Body Repair Shops", category: "Repair and Other Rental Services" },
  { code: "7534", description: "Tire Re-treading and Repair", category: "Repair and Other Rental Services" },
  { code: "7535", description: "Auto Paint Shops", category: "Repair and Other Rental Services" },
  { code: "7538", description: "Auto Service Shops", category: "Repair and Other Rental Services" },
  { code: "7542", description: "Car Washes", category: "Repair and Other Rental Services" },
  { code: "7549", description: "Towing Services", category: "Repair and Other Rental Services" },

  // Repair Services
  { code: "7622", description: "Radio Repair Shops", category: "Repair and Other Rental Services" },
  { code: "7623", description: "A/C and Refrigeration Repair Shops", category: "Repair and Other Rental Services" },
  { code: "7629", description: "Electrical and Small Appliance Repair Shops", category: "Repair and Other Rental Services" },
  { code: "7631", description: "Watch, Clock, and Jewelry Repair", category: "Repair and Other Rental Services" },
  { code: "7641", description: "Furniture Repair and Refinishing", category: "Repair and Other Rental Services" },
  { code: "7692", description: "Welding Repair", category: "Repair and Other Rental Services" },
  { code: "7699", description: "Misc. Repair Shops", category: "Repair and Other Rental Services" },

  // Entertainment
  { code: "7800", description: "Government-run Online Lotteries", category: "Entertainment Services" },
  { code: "7801", description: "Regulated Online Casinos", category: "Entertainment Services" },
  { code: "7802", description: "Regulated Events for Online Horse/Dog Racing", category: "Entertainment Services" },
  { code: "7829", description: "Motion Pictures, Video Production and Distribution", category: "Entertainment Services" },
  { code: "7832", description: "Motion Picture Theaters", category: "Entertainment Services" },
  { code: "7841", description: "Video Tape Rental Stores", category: "Entertainment Services" },
  { code: "7911", description: "Dance Halls, Studios and Schools", category: "Entertainment Services" },
  { code: "7922", description: "Theatrical Producers, Ticket Agencies", category: "Entertainment Services" },
  { code: "7929", description: "Bands, Orchestras, and Miscellaneous Entertainers", category: "Entertainment Services" },
  { code: "7932", description: "Billiard and Pool Establishments", category: "Entertainment Services" },
  { code: "7933", description: "Bowling Alleys", category: "Entertainment Services" },
  { code: "7941", description: "Sport Clubs, Fields", category: "Entertainment Services" },
  { code: "7991", description: "Tourist Attractions and Exhibits", category: "Entertainment Services" },
  { code: "7992", description: "Golf Courses - Public", category: "Entertainment Services" },
  { code: "7993", description: "Video Amusement Game Supplies", category: "Entertainment Services" },
  { code: "7994", description: "Video Game Arcades", category: "Entertainment Services" },
  { code: "7995", description: "Betting/Casino Gaming", category: "Entertainment Services" },
  { code: "7996", description: "Amusement Parks, Carnivals, Circuses", category: "Entertainment Services" },
  { code: "7997", description: "Country and Membership Clubs", category: "Entertainment Services" },
  { code: "7998", description: "Aquariums, Sea-aquariums, Dolphinariums", category: "Entertainment Services" },
  { code: "7999", description: "Misc. Recreation Services", category: "Entertainment Services" },

  // Medical
  { code: "8011", description: "Doctors and Physicians", category: "Medical Services" },
  { code: "8021", description: "Dentists and Orthodontists", category: "Medical Services" },
  { code: "8031", description: "Osteopaths", category: "Medical Services" },
  { code: "8041", description: "Chiropractors", category: "Medical Services" },
  { code: "8042", description: "Optometrists and Ophthalmologists", category: "Medical Services" },
  { code: "8043", description: "Opticians, Eyeglasses", category: "Medical Services" },
  { code: "8044", description: "Opticians, Eyeglasses (not valid for first presentments)", category: "Medical Services" },
  { code: "8049", description: "Podiatrists and Chiropodists", category: "Medical Services" },
  { code: "8050", description: "Nursing and Personal Care Facilities", category: "Medical Services" },
  { code: "8062", description: "Hospitals", category: "Medical Services" },
  { code: "8071", description: "Medical and Dental Laboratories", category: "Medical Services" },
  { code: "8099", description: "Medical Services and Health Practitioners", category: "Medical Services" },

  // Legal / Education
  { code: "8111", description: "Legal Services and Attorneys", category: "Business Services" },
  { code: "8211", description: "Elementary and Secondary Schools", category: "Educational Services and Child Care" },
  { code: "8220", description: "Colleges, Junior Colleges, Universities", category: "Educational Services and Child Care" },
  { code: "8241", description: "Correspondence Schools", category: "Educational Services and Child Care" },
  { code: "8244", description: "Business and Secretarial Schools", category: "Educational Services and Child Care" },
  { code: "8249", description: "Vocational Schools and Trade Schools", category: "Educational Services and Child Care" },
  { code: "8299", description: "Schools and Educational Services (not listed elsewhere)", category: "Educational Services and Child Care" },
  { code: "8351", description: "Child Care Services", category: "Educational Services and Child Care" },

  // Organizations
  { code: "8398", description: "Charitable and Social Service Organizations", category: "Associations/Organizations" },
  { code: "8641", description: "Civic, Fraternal, and Social Associations", category: "Associations/Organizations" },
  { code: "8651", description: "Political Organizations", category: "Associations/Organizations" },
  { code: "8661", description: "Religious Organizations", category: "Associations/Organizations" },
  { code: "8675", description: "Automobile Associations", category: "Associations/Organizations" },
  { code: "8699", description: "Membership Organizations (not listed elsewhere)", category: "Associations/Organizations" },

  // Professional
  { code: "8734", description: "Testing Laboratories (non-medical)", category: "Business Services" },
  { code: "8911", description: "Architectural - Engineering and Surveying Services", category: "Business Services" },
  { code: "8931", description: "Accounting, Auditing, and Bookkeeping Services", category: "Business Services" },
  { code: "8999", description: "Professional Services", category: "Business Services" },

  // Government
  { code: "9211", description: "Court Costs, including Alimony and Child Support", category: "Financial & Real Estate Services" },
  { code: "9222", description: "Fines", category: "Financial & Real Estate Services" },
  { code: "9223", description: "Bail and Bond Payments", category: "Financial & Real Estate Services" },
  { code: "9311", description: "Tax Payments", category: "Financial & Real Estate Services" },
  { code: "9399", description: "Government Services (not listed elsewhere)", category: "Financial & Real Estate Services" },
  { code: "9402", description: "Postal Services - Government Only", category: "Financial & Real Estate Services" },
  { code: "9405", description: "Intra - Government Transactions", category: "Financial & Real Estate Services" },
  { code: "9406", description: "Government-owned lottery non-US region", category: "Financial & Real Estate Services" },
  { code: "9700", description: "Automated Referral Service (Visa Only)", category: "Financial & Real Estate Services" },
  { code: "9751", description: "U.K. Supermarkets (Regional Use Only)", category: "Financial & Real Estate Services" },
  { code: "9752", description: "U.K. Petrol Stations (Regional Use Only)", category: "Financial & Real Estate Services" },
  { code: "9754", description: "Internet Gambling", category: "Entertainment Services" },
  { code: "9950", description: "Intra - Company Purchases (Visa Only)", category: "Financial & Real Estate Services" },
];

export const PROCESSING_PLATFORMS = [
  "Elavon - EMV",
  "First Data Omaha",
  "First Data Rapid Connect Nashville - EMV",
  "First Data Rapid Connect Nashville North - EMV",
  "First Data Rapid Connect Omaha - EMV",
  "NMI Payments",
  "WorldPay",
] as const;
