import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      // Bundled output from the @lovable.dev/mcp-js Vite plugin. Its banner
      // says "do not edit" and the plugin rewrites it on every build, so any
      // lint fix applied here would be silently reverted.
      "supabase/functions/mcp/index.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unsafe-function-type": "warn",
    },
  },
  {
    // Same story as the ignored mcp/index.ts above, one step less severe.
    //
    // Lovable's preview-auth shim is regenerated by the platform, and the
    // generator writes `let timer` where the value is assigned exactly once —
    // a `prefer-const` error. It has failed CI three times now (9880751, then
    // 8b7db17 reverting the fix from #123), and because the workflow lints
    // before it builds, that single line reds `main` and every open PR until
    // someone notices whose it is.
    //
    // `eslint --fix` cannot save us here: prefer-const will not mechanically
    // repair a `let` declared without an initializer, so the error survives
    // the fixing pass. Verified, not assumed.
    //
    // Downgraded rather than ignored. The file handles session tokens and
    // every other rule still applies to it; the const is still what belongs in
    // the source, and still there. This only stops a regenerator's stylistic
    // slip from being a repo-wide outage.
    files: ["src/integrations/supabase/previewAuthStorage.ts"],
    rules: {
      "prefer-const": "warn",
    },
  },
);
