import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    // Verify authenticated CRM admin
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return json({ error: "Unauthorized" }, 401);
    }

    const crmSupabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: authErr } = await crmSupabase.auth.getUser();
    if (authErr || !user) {
      return json({ error: "Unauthorized" }, 401);
    }

    // Check admin via is_admin_email()
    const adminSupabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: isAdmin } = await adminSupabase.rpc("is_admin_email");
    // is_admin_email runs as SECURITY DEFINER so we need to check via the user's session
    const adminEmails = ["admin@merchanthaus.io", "onboarding@merchanthaus.io", "jamie@merchanthaus.io"];
    if (!adminEmails.includes(user.email || "")) {
      return json({ error: "Admin access required" }, 403);
    }

    const { portal_merchant_id } = await req.json();
    if (!portal_merchant_id) {
      return json({ error: "portal_merchant_id required" }, 400);
    }

    // Look up merchant email from opportunities → contacts
    const { data: opp } = await adminSupabase
      .from("opportunities")
      .select("id, contact_id, contacts(email)")
      .eq("portal_merchant_id", portal_merchant_id)
      .maybeSingle();

    // Fallback: check applications table
    let merchantEmail: string | null = (opp?.contacts as any)?.email || null;

    if (!merchantEmail) {
      const { data: app } = await adminSupabase
        .from("applications")
        .select("email")
        .eq("portal_merchant_id", portal_merchant_id)
        .maybeSingle();
      merchantEmail = app?.email || null;
    }

    if (!merchantEmail) {
      return json({ error: "Merchant email not found for this portal_merchant_id" }, 404);
    }

    // Generate magic link via portal Supabase
    const portalUrl = Deno.env.get("PORTAL_SUPABASE_URL");
    const portalKey = Deno.env.get("PORTAL_SERVICE_ROLE_KEY");
    if (!portalUrl || !portalKey) {
      return json({ error: "Portal credentials not configured" }, 500);
    }

    const portalSupabase = createClient(portalUrl, portalKey);
    const { data: linkData, error: linkErr } = await portalSupabase.auth.admin.generateLink({
      type: "magiclink",
      email: merchantEmail,
    });

    if (linkErr || !linkData) {
      console.error("Magic link generation error:", linkErr);
      return json({ error: "Failed to generate portal access link" }, 500);
    }

    // Log access event to activities
    if (opp?.id) {
      await adminSupabase.from("activities").insert({
        opportunity_id: opp.id,
        type: "portal_access",
        description: `Admin ${user.email} accessed portal account for ${merchantEmail}`,
        user_id: user.id,
        user_email: user.email,
      });
    }

    console.log(`Portal access generated by ${user.email} for merchant ${merchantEmail} (${portal_merchant_id})`);

    return json({
      ok: true,
      access_url: linkData.properties?.action_link,
    });
  } catch (err) {
    console.error("Portal access error:", err);
    return json({ error: (err as Error).message }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
