export const OUTCOME_REASONS: Record<
  'closed_won' | 'closed_lost' | 'disqualified' | 'no_decision' | 'underwriting_declined',
  Array<{ value: string; label: string }>
> = {
  closed_won: [
    { value: 'competitive_pricing_ic_plus', label: 'Competitive pricing win (interchange-plus)' },
    { value: 'gateway_feature_fit_nmi', label: 'Gateway feature fit (NMI)' },
    { value: 'faster_underwriting', label: 'Faster underwriting / approval' },
    { value: 'pos_ecommerce_integration', label: 'POS / eCommerce integration match' },
    { value: 'omnichannel_cp_cnp', label: 'Omnichannel solution (CP + CNP)' },
    { value: 'high_risk_acceptance', label: 'High-risk vertical acceptance' },
    { value: 'chargeback_fraud_tools', label: 'Chargeback / fraud tool suite' },
    { value: 'relationship_referral', label: 'Relationship / referral win' },
    { value: 'contract_buyout_etf', label: 'Contract buyout / ETF coverage' },
    { value: 'white_label_branding', label: 'White-label / branding alignment' },
    { value: 'interchange_optimization', label: 'Interchange optimization' },
    { value: 'superior_onboarding', label: 'Superior onboarding experience' },
    { value: 'value_added_bundle', label: 'Value-added services bundle' },
  ],
  closed_lost: [
    { value: 'lost_flat_rate_competitor', label: 'Lost to flat-rate competitor (Square / Stripe / PayPal)' },
    { value: 'lost_iso_price', label: 'Lost to another ISO / processor on price' },
    { value: 'lost_bank_direct', label: 'Lost to bank-direct acquiring' },
    { value: 'chose_embedded_payfac', label: 'Chose embedded PayFac / software' },
    { value: 'locked_in_etf', label: 'Locked into current processor (ETF)' },
    { value: 'pricing_model_mismatch', label: 'Pricing model mismatch' },
    { value: 'gateway_integration_incompatibility', label: 'Gateway / integration incompatibility' },
    { value: 'hardware_limitations', label: 'Hardware limitations' },
    { value: 'funding_timing', label: 'Funding / settlement timing' },
    { value: 'satisfied_with_incumbent', label: 'Satisfied with incumbent processor' },
    { value: 'lost_fraud_tools', label: 'Lost on fraud / chargeback tools' },
    { value: 'volume_too_low_ic_plus', label: 'Volume too low for IC+ benefit' },
    { value: 'switching_risk_aversion', label: 'Switching risk aversion' },
    { value: 'lost_contract_terms', label: 'Lost on contract terms' },
    { value: 'decision_maker_change', label: 'Decision-maker change / restructuring' },
  ],
  disqualified: [
    { value: 'prohibited_mcc', label: 'Prohibited MCC / product category' },
    { value: 'match_tmf_hit_prescreen', label: 'Industry monitoring database hit (pre-screen)' },
    { value: 'ofac_sanctions_match', label: 'Government watchlist match' },
    { value: 'insufficient_business_history', label: 'Insufficient business history / no EIN' },
    { value: 'unacceptable_business_structure', label: 'Unacceptable business structure' },
    { value: 'volume_below_minimum', label: 'Processing volume below minimum' },
    { value: 'non_us_business', label: 'Non-U.S. domiciled business' },
    { value: 'excessive_chargeback_history', label: 'Excessive chargeback history (self-disclosed)' },
    { value: 'previously_terminated', label: 'Previously terminated by processor' },
    { value: 'pci_noncompliance_unwilling', label: 'PCI non-compliance (unwilling)' },
    { value: 'unsupported_business_model', label: 'Unsupported business model' },
    { value: 'principal_credit_disqualification', label: 'Principal credit disqualification' },
    { value: 'fraudulent_application', label: 'Fraudulent / misrepresented application' },
    { value: 'high_risk_mcc_outside_scope', label: 'High-risk MCC outside program scope' },
  ],
  no_decision: [
    { value: 'non_responsive', label: 'Merchant went non-responsive' },
    { value: 'stalled_document_collection', label: 'Stalled at document collection' },
    { value: 'internal_priority_shift', label: 'Internal priority shift' },
    { value: 'timing_not_right', label: 'Timing not right (seasonal / future need)' },
    { value: 'decision_maker_unavailable', label: 'Decision-maker unavailable' },
    { value: 'analysis_paralysis', label: 'Analysis paralysis — unable to decide' },
    { value: 'business_closure', label: 'Business closure / pre-closure' },
    { value: 'abandoned_integration', label: 'Abandoned during integration / testing' },
    { value: 'ownership_change', label: 'Ownership / management change' },
    { value: 'stalled_pci', label: 'Stalled at PCI compliance' },
    { value: 'lost_contact_info', label: 'Lost contact information' },
    { value: 'duplicate_opportunity', label: 'Duplicate opportunity' },
    { value: 'external_disruption', label: 'External disruption' },
  ],
  underwriting_declined: [
    { value: 'match_excessive_chargebacks', label: 'Industry database — excessive chargebacks' },
    { value: 'match_fraud', label: 'Industry database — fraud history' },
    { value: 'match_other', label: 'Industry database — other listing' },
    { value: 'principal_credit_below_threshold', label: 'Principal credit score below threshold' },
    { value: 'excessive_chargeback_ratio_current', label: 'Excessive chargeback ratio (current statements)' },
    { value: 'unverifiable_business_kyc', label: 'Unverifiable business / KYC failure' },
    { value: 'aml_red_flags', label: 'AML / compliance screening' },
    { value: 'financial_instability_bankruptcy', label: 'Financial instability / bankruptcy' },
    { value: 'mcc_reclassification', label: 'MCC reclassification (higher risk than presented)' },
    { value: 'website_marketing_noncompliance', label: 'Website / marketing non-compliance' },
    { value: 'volume_ticket_inconsistency', label: 'Volume / average ticket inconsistency' },
    { value: 'incomplete_docs_uw_timeout', label: 'Incomplete documentation / UW timeout' },
    { value: 'prohibited_product_discovered', label: 'Prohibited product discovered in underwriting' },
    { value: 'reserve_requirement_rejected', label: 'Reserve requirement rejected by merchant' },
    { value: 'third_party_processing', label: 'Third-party processing / aggregation discovered' },
  ],
};

export const OUTCOME_STATUS_LABELS: Record<string, string> = {
  closed_won:            'Closed Won',
  closed_lost:           'Closed Lost',
  disqualified:          'Disqualified',
  no_decision:           'No Decision / Dead',
  underwriting_declined: 'Underwriting Declined',
};

export const EMAIL_TRIGGERING_OUTCOMES: string[] = [
  'disqualified',
  'underwriting_declined',
];

export const PERMANENT_SUPPRESSION_REASONS: string[] = [
  'ofac_sanctions_match',
  'match_fraud',
  'match_excessive_chargebacks',
  'match_other',
  'match_tmf_hit_prescreen',
  'aml_red_flags',
  'fraudulent_application',
  'prohibited_mcc',
  'previously_terminated',
];

// Re-engagement task lookup: outcome_reason → { days, label }
export const REENGAGEMENT_TASKS: Record<string, { days: number; label: string }> = {
  // Closed Lost
  lost_flat_rate_competitor: { days: 90, label: 'Win-back: Compare flat-rate vs IC+ savings' },
  lost_iso_price: { days: 90, label: 'Win-back: Rate review — are they still satisfied?' },
  locked_in_etf: { days: 90, label: 'Win-back: Check if ETF window is opening' },
  satisfied_with_incumbent: { days: 180, label: 'Win-back: Incumbent processor check-in' },
  gateway_integration_incompatibility: { days: 60, label: 'Win-back: New integration may be available' },
  lost_contract_terms: { days: 120, label: 'Win-back: Terms re-offer' },
  decision_maker_change: { days: 60, label: 'Win-back: Connect with new decision-maker' },
  // No Decision / Dead
  non_responsive: { days: 30, label: 'Re-engage: Non-responsive merchant check-in' },
  timing_not_right: { days: 90, label: 'Re-engage: Timing follow-up' },
  analysis_paralysis: { days: 60, label: 'Re-engage: Decision follow-up' },
  stalled_document_collection: { days: 14, label: 'Re-engage: Missing documents reminder' },
  stalled_pci: { days: 45, label: 'Re-engage: PCI compliance check-in' },
  // Underwriting Declined (remediable only)
  principal_credit_below_threshold: { days: 180, label: 'Re-application: Credit remediation check-in' },
  excessive_chargeback_ratio_current: { days: 180, label: 'Re-application: Chargeback ratio — review progress' },
  website_marketing_noncompliance: { days: 30, label: 'Re-application: Website compliance — ready to resubmit?' },
  incomplete_docs_uw_timeout: { days: 14, label: 'Re-application: Documents ready to resubmit?' },
  reserve_requirement_rejected: { days: 90, label: 'Re-application: Reserve terms — willing to reconsider?' },
};
