import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) return json({ error: "Unauthorized" }, 401);

    const userClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: authErr } = await userClient.auth.getUser();
    if (authErr || !user) return json({ error: "Unauthorized" }, 401);

    // All authenticated CRM users (team are equal partners) may impersonate.
    // Restrict to verified team domain to prevent edge cases.
    if (!(user.email || "").toLowerCase().endsWith("@merchanthaus.io")) {
      return json({ error: "Team access required" }, 403);
    }

    const { referrer_id } = await req.json();
    if (!referrer_id) return json({ error: "referrer_id required" }, 400);

    const admin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: ref, error: refErr } = await admin
      .from("referrers")
      .select("id, email, full_name, active")
      .eq("id", referrer_id)
      .maybeSingle();

    if (refErr || !ref) return json({ error: "Referrer not found" }, 404);
    if (!ref.active) return json({ error: "Referrer account is inactive" }, 400);

    const origin = req.headers.get("origin") || req.headers.get("referer") || "";
    const redirectTo = origin ? `${origin.replace(/\/$/, "")}/affiliate` : undefined;

    const { data: linkData, error: linkErr } = await admin.auth.admin.generateLink({
      type: "magiclink",
      email: ref.email,
      options: redirectTo ? { redirectTo } : undefined,
    });

    if (linkErr || !linkData) {
      console.error("Magic link error", linkErr);
      return json({ error: linkErr?.message || "Failed to generate magic link" }, 500);
    }

    // Audit log
    await admin.from("referrer_impersonation_logs").insert({
      referrer_id: ref.id,
      referrer_email: ref.email,
      admin_user_id: user.id,
      admin_email: user.email,
    });

    console.log(`Impersonation link generated by ${user.email} for ${ref.email}`);

    return json({
      ok: true,
      access_url: linkData.properties?.action_link,
      referrer_email: ref.email,
    });
  } catch (err) {
    console.error("impersonate-referrer error", err);
    return json({ error: (err as Error).message }, 500);
  }
});
