// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-opportunities.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/_result.ts
function toJson(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }]
  };
}
function toError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function notAuthenticated() {
  return toError("Not authenticated. Reconnect this integration and sign in again.");
}

// src/lib/mcp/tools/list-opportunities.ts
var list_opportunities_default = defineTool({
  name: "list_opportunities",
  title: "List opportunities",
  description: "List CRM pipeline opportunities visible to the signed-in user, optionally filtered by stage or assignee.",
  inputSchema: {
    stage: z.string().trim().min(1).optional().describe("Pipeline stage to filter by, e.g. 'discovery'."),
    assigned_to: z.string().trim().min(1).optional().describe("Assignee name or email to filter by."),
    limit: z.number().int().min(1).max(100).optional().describe("Maximum rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, assigned_to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("opportunities").select(
      "id, stage, status, service_type, assigned_to, outcome_status, created_at, stage_entered_at, accounts(name, website, city, state)"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (stage) query = query.eq("stage", stage);
    if (assigned_to) query = query.eq("assigned_to", assigned_to);
    const { data, error } = await query;
    if (error) return toError(error.message);
    return toJson({ count: data?.length ?? 0, opportunities: data ?? [] });
  }
});

// src/lib/mcp/tools/get-opportunity.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_opportunity_default = defineTool2({
  name: "get_opportunity",
  title: "Get opportunity",
  description: "Fetch one pipeline opportunity by id, including its account and primary contact details.",
  inputSchema: {
    opportunity_id: z2.string().uuid().describe("The opportunity's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ opportunity_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("opportunities").select(
      "id, stage, status, service_type, pricing_plan, gateway_tier, assigned_to, source, referral_source, outcome_status, outcome_reason, created_at, stage_entered_at, accounts(id, name, website, city, state, country, commission_model), contacts(id, first_name, last_name, email, phone)"
    ).eq("id", opportunity_id).maybeSingle();
    if (error) return toError(error.message);
    if (!data) return toError("No opportunity found with that id, or it is not visible to you.");
    return toJson(data);
  }
});

// src/lib/mcp/tools/search-accounts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_accounts_default = defineTool3({
  name: "search_accounts",
  title: "Search accounts",
  description: "Search merchant accounts by name, with their location, website and commission model.",
  inputSchema: {
    query: z3.string().trim().min(1).optional().describe("Partial account name to search for."),
    limit: z3.number().int().min(1).max(100).optional().describe("Maximum rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let builder = supabase.from("accounts").select("id, name, website, city, state, country, status, commission_model, nmi_merchant_id, created_at").order("name", { ascending: true }).limit(limit ?? 25);
    if (query) builder = builder.ilike("name", `%${query}%`);
    const { data, error } = await builder;
    if (error) return toError(error.message);
    return toJson({ count: data?.length ?? 0, accounts: data ?? [] });
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "List tasks",
  description: "List team tasks, optionally filtered by status or assignee email.",
  inputSchema: {
    status: z4.string().trim().min(1).optional().describe("Task status to filter by, e.g. 'open'."),
    assignee: z4.string().trim().min(1).optional().describe("Assignee email to filter by."),
    limit: z4.number().int().min(1).max(100).optional().describe("Maximum rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, assignee, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let builder = supabase.from("tasks").select("id, title, description, status, priority, assignee, created_by, due_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) builder = builder.eq("status", status);
    if (assignee) builder = builder.eq("assignee", assignee);
    const { data, error } = await builder;
    if (error) return toError(error.message);
    return toJson({ count: data?.length ?? 0, tasks: data ?? [] });
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_task_default = defineTool5({
  name: "create_task",
  title: "Create task",
  description: "Create a task in the Ops Terminal, assigned to a team member by email.",
  inputSchema: {
    title: z5.string().trim().min(1).max(200).describe("Short task title."),
    description: z5.string().trim().max(2e3).optional().describe("Optional task detail."),
    assignee: z5.string().trim().email().optional().describe("Assignee email address."),
    priority: z5.enum(["low", "medium", "high"]).optional().describe("Task priority (default medium)."),
    due_at: z5.string().trim().optional().describe("Optional ISO 8601 due date/time.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, assignee, priority, due_at }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      title,
      description: description ?? null,
      assignee: assignee ?? null,
      priority: priority ?? "medium",
      due_at: due_at ?? null,
      status: "open",
      created_by: ctx.getUserEmail() ?? null,
      source: "mcp"
    }).select().maybeSingle();
    if (error) return toError(error.message);
    return toJson({ created: data });
  }
});

// src/lib/mcp/tools/list-support-tickets.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_support_tickets_default = defineTool6({
  name: "list_support_tickets",
  title: "List support tickets",
  description: "List support tickets with subject, requester, status and priority. Archived tickets are excluded unless requested.",
  inputSchema: {
    status: z6.string().trim().min(1).optional().describe("Ticket status to filter by, e.g. 'open' or 'closed'."),
    include_archived: z6.boolean().optional().describe("Include archived tickets (default false)."),
    limit: z6.number().int().min(1).max(100).optional().describe("Maximum rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let builder = supabase.from("support_tickets").select(
      "id, ticket_number, subject, category, priority, status, source, requester_name, requester_email, assigned_to_email, created_at, closed_at, archived_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) builder = builder.eq("status", status);
    if (!include_archived) builder = builder.is("archived_at", null);
    const { data, error } = await builder;
    if (error) return toError(error.message);
    return toJson({ count: data?.length ?? 0, tickets: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "cuqjaddtmkotgvfsgcol";
var mcp_default = defineMcp({
  name: "the-ops-terminal",
  title: "The Ops Terminal",
  version: "0.1.0",
  instructions: "Tools for The Ops Terminal, a merchant payments CRM. Use `search_accounts` to find merchant accounts, `list_opportunities` and `get_opportunity` for pipeline deals, `list_support_tickets` for the support queue, and `list_tasks` / `create_task` for team tasks. All calls run as the signed-in user, so results respect that user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_accounts_default,
    list_opportunities_default,
    get_opportunity_default,
    list_support_tickets_default,
    list_tasks_default,
    create_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
